.github/workflows/publish-chromatic.yml

Chromatic working directory was not defined in CI
Chromatic CI should be able to execute Publish
No

Fix - Chromatic CI working directory

---

apps/docs/package.json
apps/web/package.json
package-lock.json
package.json
packages/visu/package.json
packages/visu/vite.config.ts

Added Next.JS App Router support by adding 'use client' to build banner. In server components it is now possible to use Visu components, but all components are client side.
Updated typescript version to 5.2.2
Fixed exports type
No

Feature - Update to add Next.JS App Router support

---

apps/docs/package.json
apps/web/package.json
package-lock.json
package.json
packages/tsconfig/package.json
packages/visu/package.json

Release 2.2.0

---

packages/visu/src/library/Icon/index.tsx
packages/visu/src/theme/theme-plugin.js

The icon component was breaking at small sizes because it didn't have a minimum width size
The Icon component will not break at small sizes
No

Fix - Icon min width

---

packages/visu/src/library/Avatar/Root.tsx

Replaced outline with border to keep outline for accessibility
When Avatar have tabIndex=0 the outline will be visible for accessibility
No

Fix - Avatar accessibility

---

apps/docs/src/index.stories.mdx
apps/docs/src/stories/components.stories.mdx
packages/visu/README.md

Updated readme and storybook docs for components without tailwindcss

Documentation - Updated readme and storybook docs for components without tailwindcss

---

apps/docs/package.json
apps/web/package.json
package-lock.json
package.json
packages/tsconfig/package.json
packages/visu/package.json

chore: release version 2.2.2

---

apps/docs/package.json
apps/web/package.json
package-lock.json
package.json
packages/tsconfig/package.json
packages/visu/package.json
scripts/versioning

chore: release version 2.3.0

---

apps/docs/package.json
apps/web/package.json
package-lock.json
package.json
packages/tsconfig/package.json
packages/visu/package.json

release: 2.4.0

---

apps/docs/package.json
apps/web/package.json
package-lock.json
package.json
packages/tsconfig/package.json
packages/visu/package.json

release: 2.5.0

---

apps/docs/package.json
apps/web/package.json
package-lock.json
package.json
packages/tsconfig/package.json
packages/visu/package.json

release: 2.6.0

---

apps/docs/src/stories/Tooltip/Close.stories.tsx
apps/docs/src/stories/Tooltip/Hover.stories.tsx
packages/visu/src/App.tsx
packages/visu/src/__tests__/Tooltip/Close.test.tsx
packages/visu/src/__tests__/Tooltip/Hover.test.tsx
packages/visu/src/library/Tooltip/Close.tsx
packages/visu/src/library/Tooltip/Hover.tsx

- adição de closeTime no Tooltip.Close
- adição de closeButton no Tooltip.Close (botão agora é opcional, mas o padrão ainda é true)
no

feat: close button with close time

---

apps/docs/package.json
apps/web/package.json
package-lock.json
package.json
packages/tsconfig/package.json
packages/visu/package.json

release: 2.6.1

---

docs/package.json
package-lock.json
package.json
package/package.json
scripts/versioning.js

release: 2.6.2

---

docs/package.json
package-lock.json
package.json
package/package.json

release: 3.0.0

---

docs/package.json
package-lock.json
package.json
package/package.json

release: 3.0.1

---

docs/package.json
package-lock.json
package.json
package/package.json

release: 3.1.0

---

package-lock.json
package/src/App.tsx
package/src/library/Toggle/Item.tsx

fix: toggle styles

---

README.md
docs/package.json
package-lock.json
package.json
package/package.json

Release 3.1.1

---

package/src/library/Form/Label.tsx

fix: form group type

---

docs/package.json
package-lock.json
package.json
package/package.json

release: 3.2.0

---

package-lock.json
package/src/library/Toast/Root.tsx

chore: toast colors

---

docs/package.json
package-lock.json
package.json
package/package.json

release: 3.3.0

---

docs/package.json
package-lock.json
package.json
package/package.json

chore: bump version

---

docs/package.json
package-lock.json
package.json
package/package.json

**Resolves issue:**
Issue link if existis
A small summary of changes that can be understood by non-devs.
**Code changes:**
- feat|chore|fix XXXXXX
**Observation:**
Some additional information. (Optional)

release: 3.4.1

---

docs/package.json
package-lock.json
package.json
package/package.json

**Resolves issue:**
Issue link if existis
A small summary of changes that can be understood by non-devs.
**Code changes:**
- feat|chore|fix XXXXXX
**Observation:**
Some additional information. (Optional)

release: 3.5.0

---

docs/package.json
package-lock.json
package.json
package/package.json

**Resolves issue:**
Issue link if existis
A small summary of changes that can be understood by non-devs.
**Code changes:**
- feat|chore|fix XXXXXX
**Observation:**
Some additional information. (Optional)

Release 3.6.0

---

package/src/library/DatePicker/index.tsx

maledeto datepicker 

---

package/src/App.tsx
package/src/library/Select/Root.tsx

Add scrollable option to Select component

Add scrollable option to Select component

---

docs/package.json
package-lock.json
package.json
package/package.json

Release 3.6.2
